---
abstract: 'A non-blocking Graphite (http://graphite.wikidot.com/) client'
author:
  - 'Joshua Barratt <josh@mediatemple.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Graphite
provides:
  AnyEvent::Graphite:
    file: lib/AnyEvent/Graphite.pm
    version: 0.08
  AnyEvent::Graphite::SNMPAgent:
    file: lib/AnyEvent/Graphite/SNMPAgent.pm
requires:
  AnyEvent: 0
  AnyEvent::SNMP: 0
  Net::SNMP: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
